expenses_tracker/expenses_tracker/expenses_profile/urls.py
from django.urls import path

from expenses_tracker.expenses_profile.views import profile_page, edit_profile, delete_profile

urlpatterns = [
	path('', profile_page, name='profile page'),
	path('edit/', edit_profile, name='edit profile'),
	path('delete/', delete_profile, name='delete profile'),
]

expenses_tracker/expenses_tracker/expenses_tracker/urls.py
from django.urls import path

from expenses_tracker.expenses_tracker.views import home_page, edit_expense, create_expense, delete_expense

urlpatterns = [
	path('', home_page, name='home page'),
	path('create/', create_expense, name='create expense'),
	path('edit/<int:pk>/', edit_expense, name='edit expense'),
	path('delete/<int:pk>/', delete_expense, name='delete expense'),
]

expenses_tracker/expenses_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include('expenses_tracker.expenses_tracker.urls')),
	path('profile/', include('expenses_tracker.expenses_profile.urls')),
]

expenses_tracker/expenses_tracker/expenses_profile/models.py
from django.db import models


class Profile(models.Model):
	first_name = models.CharField(
		max_length=15,
	)
	last_name = models.CharField(
		max_length=15,
	)
	budget = models.IntegerField()

	def __str__(self):
		return f'{self.first_name} {self.last_name}'

expenses_tracker/expenses_tracker/expenses_tracker/models.py
from django.db import models


class Expense(models.Model):
	title = models.CharField(
		max_length=50,
	)
	image_url = models.URLField()
	description = models.TextField()
	price = models.FloatField()

	def __str__(self):
		return self.title

expenses_tracker/expenses_tracker/expenses_profile/forms.py
from django import forms

from expenses_tracker.expenses_profile.models import Profile


class ProfileForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = '__all__'

expenses_tracker/expenses_tracker/expenses_tracker/forms.py
from django import forms

from expenses_tracker.expenses_tracker.models import Expense


class ExpenseForm(forms.ModelForm):
	class Meta:
		model = Expense
		fields = '__all__'

expenses_tracker/expenses_tracker/expenses_profile/views.py
from django.shortcuts import render, redirect

from expenses_tracker.expenses_profile.forms import ProfileForm
from expenses_tracker.expenses_profile.models import Profile
from expenses_tracker.utils.utils import money_left


def profile_page(request):
	context = {
		'profile': Profile.objects.first(),
		'money_left': money_left(),
	}
	return render(request, 'profile.html', context)


def create_profile(request):
	if request.method == 'GET':
		context = {
			'form': ProfileForm(),
		}
		return render(request, 'home-no-profile.html', context)
	create_form = ProfileForm(request.POST)
	if create_form.is_valid():
		create_form.save()
		return redirect('home page')


def edit_profile(request):
	profile = Profile.objects.first()
	if request.method == 'GET':
		context = {
			'profile_form': ProfileForm(initial=profile.__dict__),
		}
		return render(request, 'profile-edit.html', context)
	else:
		form = ProfileForm(
			request.POST,
			instance=profile,
		)
		if form.is_valid():
			form.save()
			return redirect('profile page')
		context = {'form': form}
		return render(request, 'profile-edit.html', context)


def delete_profile(request):
	if request.method == 'GET':
		return render(request, 'profile-delete.html')
	Profile.objects.first().delete()
	return redirect('/')

expenses_tracker/expenses_tracker/expenses_tracker/views.py
from django.shortcuts import render, redirect

from expenses_tracker.expenses_profile.models import Profile
from expenses_tracker.expenses_profile.views import create_profile
from expenses_tracker.expenses_tracker.forms import ExpenseForm
from expenses_tracker.expenses_tracker.models import Expense
from expenses_tracker.utils.utils import money_left


def home_page(request):
	profile = Profile.objects.first()
	if not profile:
		return create_profile(request)
	context = {
		'profile': profile,
		'expenses': Expense.objects.all(),
		'money_left': money_left(),
	}
	return render(request, 'home-with-profile.html', context)


def create_expense(request):
	if request.method == "GET":
		context = {'form': ExpenseForm()}
		return render(request, 'expense-create.html', context)
	form = ExpenseForm(request.POST)
	if form.is_valid():
		form.save()
		return redirect('home page')
	context = {'form': form}
	return redirect(request, 'expense-create.html', context)


def edit_expense(request, pk):
	expense = Expense.objects.get(pk=pk)
	form = ExpenseForm(initial=expense.__dict__)
	if request.method == 'GET':
		context = {'form': form}
		return render(request, 'expense-edit.html', context)
	form = ExpenseForm(request.POST, instance=expense)
	if form.is_valid():
		form.save()
		return redirect('home page')
	context = {'form': form}
	return render(request, 'expense-edit.html', context)


def delete_expense(request, pk):
	expense = Expense.objects.get(pk=pk)
	form = ExpenseForm(initial=expense.__dict__)
	if request.method == 'GET':
		context = {'form': form}
		return render(request, 'expense-delete.html', context)
	expense.delete()
	return redirect('home page')

expenses_tracker/templates/expense-create.html
{% load static %}
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="../static/css/style.css">
    <title>Expenses Tracker</title>
</head>

<body>

<nav>
    <ul>
        <li class="img"><img src="{% static "images/dollar.png" %}" alt=""></li>
        <li><a href="/">Expenses Tracker</a></li>

        <li class="right"><a href="{% url "profile page" %}">Profile</a></li>

    </ul>
</nav>
    <div class="body">

<h1>Create Expense</h1>
<div class="form">
    <form method="POST">
		{% csrf_token %}
		{{ form }}
{#        <input type="hidden" name="csrfmiddlewaretoken" value="HUrRfZ1Xv8I1kg0RCRhg5I8sTJMRfcaLEI9Pf4LGjQXUjsQgoxLnWAleb0K01njw">#}
{#        <label for="name">Title</label>#}
{#        <input type="text" name="title" maxlength="50" required="" id="id_title">#}
{##}
{#        <label for="description">Description</label>#}
{#        <textarea name="description" cols="40" rows="10" required="" id="id_description"></textarea>#}
{##}
{#        <label for="imageUrl">Link to Image</label>#}
{#        <input type="url" name="image_url" maxlength="200" required="" id="id_image_url">#}
{##}
{#        <label for="price">Price</label>#}
{#        <input type="number" name="price" step="any" required="" id="id_price">#}

        <input type="submit" value="Create">
    </form>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

expenses_tracker/templates/expense-delete.html
{% load static %}
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
    <title>Expenses Tracker</title>
</head>

<body>

<nav>
    <ul>
        <li class="img"><img src="{% static "images/dollar.png" %}" alt=""></li>
        <li><a href="/">Expenses Tracker</a></li>

        <li class="right"><a href="{% url "profile page" %}">Profile</a></li>

    </ul>
</nav>
    <div class="body">

<h1>Delete Expense</h1>
<div class="form">
    <form method="POST">
		{% csrf_token %}
		{{ form }}
{#        <input type="hidden" name="csrfmiddlewaretoken" value="hwapnt8nZjnQuJ2M6SZBuXGgOwc3fZlrekSnnyS6N1CJtVSbSytIlPT26Nac1auc">#}
{#        <label for="name">Title</label>#}
{#        <input type="text" name="title" value="Electrical Piano" maxlength="50" disabled="" required="" id="id_title">#}
{##}
{#        <label for="description">Description</label>#}
{#        <textarea name="description" cols="40" rows="10" disabled="" required="" id="id_description">I bought myself a new piano to improve my skills</textarea>#}
{##}
{#        <label for="image_url">Link to Image</label>#}
{#        <input type="url" name="image_url" value="https://www.pngkit.com/png/full/307-3075914_free-piano-clipart-piano-png.png" maxlength="200" disabled="" required="" id="id_image_url">#}
{##}
{#        <label for="price">Price</label>#}
{#        <input type="number" name="price" value="1000.0" step="any" disabled="" required="" id="id_price">#}

        <input type="submit" value="Delete">
    </form>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

expenses_tracker/templates/expense-edit.html
{% load static %}
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
    <title>Expenses Tracker</title>
</head>

<body>

<nav>
    <ul>
        <li class="img"><img src="{% static "images/dollar.png" %}" alt=""></li>
        <li><a href="/">Expenses Tracker</a></li>

        <li class="right"><a href="{% url "profile page" %}">Profile</a></li>

    </ul>
</nav>
    <div class="body">

<h1>Edit Expense</h1>
<div class="form">
    <form method="POST">
		{% csrf_token %}
		{{ form }}
{#        <input type="hidden" name="csrfmiddlewaretoken" value="E8qoLvlyiXBfE7NlcyWlXe1TMWV5qvo7BW8mLA5h6FQ8DjDKYeqsO6eF4dTecGxS">#}
{#        <label for="name">Title</label>#}
{#        <input type="text" name="title" value="Electrical Piano" maxlength="50" required="" id="id_title">#}
{##}
{#        <label for="description">Description</label>#}
{#        <textarea name="description" cols="40" rows="10" required="" id="id_description">I bought myself a new piano to improve my skills</textarea>#}
{##}
{#        <label for="image_url">Link to Image</label>#}
{#        <input type="url" name="image_url" value="https://www.pngkit.com/png/full/307-3075914_free-piano-clipart-piano-png.png" maxlength="200" required="" id="id_image_url">#}
{##}
{#        <label for="price">Price</label>#}
{#        <input type="number" name="price" value="1000.0" step="any" required="" id="id_price">#}

        <input type="submit" value="Edit">
    </form>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

expenses_tracker/templates/home-no-profile.html
{% load static %}
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
    <title>Expenses Tracker</title>
</head>

<body>

<nav>
    <ul>
        <li class="img"><img src="{% static "images/dollar.png"%}" alt=""></li>
        <li><a href="/">Expenses Tracker</a></li>

    </ul>
</nav>
    <div class="body">

<h1>Enter your data</h1>
<div class="form">
    <form method="POST">
		{% csrf_token %}
		{{ form }}
{#        <input type="hidden" name="csrfmiddlewaretoken" value="97MmAxmrs7yPXUamEdIgRY80OHEP383f6VukAC6agPNIW60LqTcnIQlM6YCYPjc0">#}
{#        <label for="budget">Budget</label>#}
{#        <input type="number" name="budget" required="" id="id_budget">#}
{##}
{#        <label for="firstName">First Name</label>#}
{#        <input type="text" name="first_name" maxlength="15" required="" id="id_first_name">#}
{##}
{#        <label for="lastName">Last Name</label>#}
{#        <input type="text" name="last_name" maxlength="15" required="" id="id_last_name">#}

        <input type="submit" value="Submit">
    </form>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

expenses_tracker/templates/home-with-profile.html
{% load static %}
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
    <title>Expenses Tracker</title>
</head>

<body>

<nav>
    <ul>
        <li class="img"><img src="{% static "images/dollar.png"%}" alt=""></li>
        <li><a href="/">Expenses Tracker</a></li>

        <li class="right"><a href="{% url "profile page" %}">Profile</a></li>

    </ul>
</nav>
    <div class="body">

{% if expenses %}
<div>
    <h1>Summary</h1><h1>

    <ul class="expenses-list">
    <li class="blue">{{ profile.budget }}$</li>
	{% for exp in expenses %}
        <li class="red"> - {{ exp.price }}$</li>
	{% endfor %}
    <li class="green">= {{ money_left }}$ left</li>

    </ul>
</h1></div>
{% endif %}
<h1>My Expenses</h1>
		{% csrf_token %}
<div class="button add-expense">
<a href="{% url "create expense" %}">Add Expense</a>
</div>

<div class="expenses-container">
{% for exp in expenses %}
        <div class="expense-container">
    <h2>{{ exp.title }}</h2>
    <hr>
    <img src="{{ exp.image_url }}" alt="">
    <p>{{ exp.description }}</p>
    <div class="expense-detail">
        <div>
            <p>Price: {{ exp.price }}$</p>
        </div>
        <div class="right">
            <a class="button edit" href="{% url "edit expense" exp.id %}">Edit</a>
            <a class="button delete" href="{% url "delete expense" exp.id %}">Delete</a>
        </div>
    </div>
</div>
{% endfor %}

</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

expenses_tracker/templates/profile-delete.html
{% load static %}
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
    <title>Expenses Tracker</title>
</head>

<body>

<nav>
    <ul>
        <li class="img"><img src="{% static "images/dollar.png" %}" alt=""></li>
        <li><a href="/">Expenses Tracker</a></li>

        <li class="right"><a href="{% url "profile page" %}">Profile</a></li>

    </ul>
</nav>
    <div class="body">

<h1>Are you sure you want to delete your profile?</h1>
<form method="POST">
{% csrf_token %}
<button class="button">Confirm</button>
</form>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

expenses_tracker/templates/profile-edit.html
{% load static %}
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
    <title>Expenses Tracker</title>
</head>

<body>

<nav>
    <ul>
        <li class="img"><img src="{% static "images/dollar.png" %}" alt=""></li>
        <li><a href="/">Expenses Tracker</a></li>

        <li class="right"><a href="{% url "profile page" %}">Profile</a></li>

    </ul>
</nav>
    <div class="body">

<h1>Enter your new data</h1>
<div class="form">
    <form method="POST">
		{% csrf_token %}
		{{ profile_form }}
{#        <input type="hidden" name="csrfmiddlewaretoken" value="M6BlBJtidtTAjIVkeKKrO0pzGsJVBeMuJUjjBOd11b8tiULJ0qeyFSClYJH4npVf">#}
{#        <label for="budget">Budget</label>#}
{#        <input type="number" name="budget" value="1500" required="" id="id_budget">#}
{##}
{#        <label for="firstName">First Name</label>#}
{#        <input type="text" name="first_name" value="Tanya" maxlength="15" required="" id="id_first_name">#}
{##}
{#        <label for="lastName">Last Name</label>#}
{#        <input type="text" name="last_name" value="Staneva" maxlength="15" required="" id="id_last_name">#}

        <input type="submit" value="Edit">
    </form>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

expenses_tracker/templates/profile.html
{% load static %}
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
    <title>Expenses Tracker</title>
</head>

<body>

<nav>
    <ul>
        <li class="img"><img src="{% static "images/dollar.png" %}" alt=""></li>
        <li><a href="/">Expenses Tracker</a></li>

        <li class="right"><a href="{% url 'profile page' %}">Profile</a></li>

    </ul>
</nav>
    <div class="body">

<h1>Your Profile</h1>
<div class="expenses-container">
    <div class="expense-container">
        <h2>{{ profile.first_name }}  {{ profile.last_name }}</h2>
        <hr>
        <img src="{% static "images/user.png" %}" alt="">
        <p>In your profile you can edit your profile data</p>
        <div class="expense-detail">
            <div>
                <p>Budget Left: {{ money_left }}$</p>
            </div>
            <div class="right">
                <a class="button edit" href="{% url "edit profile" %}">Edit Profile</a>
                <a class="button delete" href="{% url "delete profile" %}">Delete Profile</a>
            </div>
        </div>
    </div>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>